import { execFileSync } from 'child_process'
import { writeFileSync } from 'fs'
import { allCssProperties } from '../src/properties'
import { readCssPropertyValues } from './css-values'

const run = () => {
  const outputPath = './src/values.ts'
  const values = readCssPropertyValues(allCssProperties)

  // Interned and encoded rather than emitted as JSON. 611 properties share 262 keyword sets —
  // almost all of the sharing is the named-colour list — so writing one per property is 180kB
  // where this is 57kB. Build-time only: nothing here reaches a browser.
  const groups = values.groups.map((keywords) => keywords.join(',')).join(';')
  const byProperty = Object.entries(values.byProperty)
    .map(([property, index]) => `${property}:${index}`)
    .join(',')

  writeFileSync(
    outputPath,
    `
  /**
   * Generated by \`pnpm values\`. What each CSS property accepts, as data.
   *
   * The generated types have always carried the same facts —
   * \`KnownKeywords<CssProperties["top"]>\` *is* the keyword list below — but only TypeScript
   * could read them. That put every correctness question behind a type-check: expensive,
   * invisible to a template or a spread object, and unable to say more than "not assignable".
   * As data, the build can answer instead, where the tokens already are.
   */

  const cssGlobalKeywordsStr = "${values.globals.join(',')}";
  /** The css-wide keywords, which every property takes and none needs to list. */
  const cssGlobalKeywords: ReadonlySet<string> = new Set(cssGlobalKeywordsStr.split(','))

  const keywordGroupsStr = "${groups}";
  const keywordGroups = keywordGroupsStr.split(';').map((group) => (group ? group.split(',') : []))

  const keywordGroupByPropertyStr = "${byProperty}";
  const keywordGroupByProperty = new Map(
    keywordGroupByPropertyStr.split(',').map((entry) => {
      const at = entry.lastIndexOf(':')
      return [entry.slice(0, at), Number(entry.slice(at + 1))] as const
    }),
  )

  const cache = new Map<string, ReadonlySet<string>>()

  /**
   * The keywords a css property enumerates, css-wide keywords included.
   *
   * Empty for a property csstype does not describe, which is *not* the same as "takes nothing":
   * a caller must read an empty set as no opinion rather than as a rejection, or every custom
   * utility mapping to a css variable becomes an error.
   */
  const cssPropertyKeywords = (prop: string): ReadonlySet<string> => {
    let keywords = cache.get(prop)
    if (keywords) return keywords

    const group = keywordGroupByProperty.get(prop)
    keywords = group === undefined ? new Set() : new Set([...keywordGroups[group]!, ...cssGlobalKeywords])
    cache.set(prop, keywords)
    return keywords
  }

  const authorIdentPropertiesStr = "${values.authorIdent.join(',')}";
  const authorIdentProperties = new Set(authorIdentPropertiesStr.split(','))

  /**
   * Does this property's grammar admit an identifier the author invents — a \`@keyframes\` name,
   * a grid line, a font family, a counter, a transition property?
   *
   * csstype cannot answer it: \`top\` and \`animationName\` are both \`… | (string & {})\` there,
   * one because it takes lengths and the other because it takes a \`<custom-ident>\`. mdn's
   * grammar draws the line, and it is the whole difference between \`top: 'navH'\` being a typo
   * and \`animationName: 'fadeIn'\` being ordinary.
   */
  const acceptsAuthorIdent = (prop: string) => authorIdentProperties.has(prop)

  export { acceptsAuthorIdent, cssGlobalKeywords, cssPropertyKeywords }
`,
  )

  try {
    execFileSync('oxfmt', [outputPath], { stdio: 'ignore' })
  } catch {
    // oxfmt not available
  }
}

run()
