import type { Context } from '@bamboocss/core'
import { groupClassName } from '@bamboocss/shared'
import { outdent } from 'outdent'

/**
 * The grouped class names an encoder has accumulated.
 *
 * Derived through `groupClassName`, the same function the browser runtime calls — a
 * registry built any other way would be a third spelling of a name that already has two.
 * Unescaped, unlike `StyleDecoder`'s class names: this is compared against what `css()`
 * returns into a `class` attribute, not against a selector.
 *
 * Reads from the encoder rather than the decoder so it is available as soon as extraction
 * is, and so `codegen` can emit whatever is already known instead of blanking the file.
 */
export function collectGroupClassNames(ctx: Pick<Context, 'encoder' | 'utility'>): string[] {
  const names: string[] = []
  ctx.encoder.grouped.forEach((_hashes, groupId) => {
    names.push(groupClassName(groupId, ctx.utility.toHash, ctx.utility.formatClassName))
  })
  return names.sort()
}

/**
 * The grouped classes the build emitted a rule for.
 *
 * Under `cssMode: 'grouped'` a class names a whole `css()` call, so the build has to have
 * seen that exact call to emit its rule. This is how the runtime tells the difference: a
 * class in here has CSS behind it, and one that is not falls back to naming its
 * declarations atomically as well.
 *
 * Written by two passes. `codegen` emits whatever the encoder already holds — usually
 * nothing, since it runs on config change before anything is extracted, but not blank when
 * it runs after a build. The CSS build then rewrites it with the set it emitted.
 *
 * An empty or stale registry is safe by construction: the runtime *adds* to the group class
 * rather than replacing it, so the worst a miss can do is name a class that matches nothing.
 */
export function generateGroupRegistry(ctx: Pick<Context, 'encoder' | 'utility'>, classNames?: string[]) {
  // A sorted, comma-joined string rather than an array literal: it is one token for the
  // minifier and compresses far better than n quoted strings, and the runtime only ever
  // needs membership.
  const names = classNames ?? collectGroupClassNames(ctx)
  const packed = JSON.stringify(names.slice().sort().join(','))

  return {
    js: outdent`
    // Generated by bamboo. Rewritten on every CSS build — do not edit.
    const packed = ${packed}

    export const groups = /* @__PURE__ */ new Set(packed ? packed.split(',') : [])
    `,
    dts: outdent`
    /**
     * The grouped classes this build emitted a rule for. Internal — the generated \`css\`
     * consults it to decide whether a grouped class has CSS behind it.
     */
    export declare const groups: Set<string>;
    `,
  }
}

/** Where the registry lives, so the writer and the importer cannot disagree about it. */
export const GROUP_REGISTRY_FILE = 'groups'
