import { describe, expect, test } from 'vitest'
import { readCssPropertyValues } from '../scripts/css-values'
import { acceptsAuthorIdent, allCssProperties, cssGlobalKeywords, cssPropertyKeywords } from '../src'

/**
 * What a CSS property accepts, as data the build can read.
 *
 * The same facts have always been in the generated types — `KnownKeywords<CssProperties["top"]>`
 * *is* this keyword list — but only TypeScript could read them, which is why checking a value
 * meant paying for a type-check and why the diagnostic could never say more than "not
 * assignable". These are the inputs that let the resolver answer instead.
 *
 * Asserted by behaviour on real properties rather than by snapshotting 611 entries: the table is
 * regenerated from csstype and mdn-data, so a snapshot would only restate whatever those two say
 * this week. What must hold is the *distinction* each source exists to draw.
 */
describe('css property keywords', () => {
  test('enumerates what a closed property takes', () => {
    const position = cssPropertyKeywords('position')

    expect(position.has('sticky')).toBe(true)
    expect(position.has('absolute')).toBe(true)
    expect(position.has('stickyy')).toBe(false)
  })

  test('resolves through csstype’s shared data types', () => {
    // `display` is `DisplayOutside | DisplayInside | …`, and `color` reaches the named-colour
    // list two aliases deep. Both were empty while the namespace parser stopped at the first
    // line-initial brace, and nothing said so — the sets were simply small.
    expect(cssPropertyKeywords('display').has('flex')).toBe(true)
    expect(cssPropertyKeywords('display').has('inline-block')).toBe(true)
    expect(cssPropertyKeywords('color').has('rebeccapurple')).toBe(true)
    expect(cssPropertyKeywords('color').size).toBeGreaterThan(100)
  })

  test('every property takes the css-wide keywords', () => {
    expect([...cssGlobalKeywords].sort()).toEqual([
      '-moz-initial',
      'inherit',
      'initial',
      'revert',
      'revert-layer',
      'unset',
    ])

    for (const prop of ['top', 'display', 'color', 'zIndex']) {
      expect(cssPropertyKeywords(prop).has('inherit'), prop).toBe(true)
      expect(cssPropertyKeywords(prop).has('unset'), prop).toBe(true)
    }
  })

  /**
   * An empty set is "csstype does not describe this", not "this property takes nothing". A
   * caller that reads it as a rejection would fail every custom utility that maps to a css
   * variable.
   */
  test('says nothing about a property it does not know', () => {
    expect(cssPropertyKeywords('notAProperty').size).toBe(0)
  })
})

describe('author identifiers', () => {
  /**
   * The distinction csstype cannot express. `top` and `animationName` are both
   * `… | (string & {})` there — one because it takes lengths, the other because it takes a
   * `<custom-ident>` — so the type layer had to carry a hand-written list of 29 property names
   * to know the difference. mdn's grammar says it outright.
   */
  test('separates a length-taking property from an identifier-taking one', () => {
    expect(acceptsAuthorIdent('top')).toBe(false)
    expect(acceptsAuthorIdent('zIndex')).toBe(false)
    expect(acceptsAuthorIdent('boxShadow')).toBe(false)

    expect(acceptsAuthorIdent('animationName')).toBe(true)
    expect(acceptsAuthorIdent('gridArea')).toBe(true)
    expect(acceptsAuthorIdent('fontFamily')).toBe(true)
    expect(acceptsAuthorIdent('counterReset')).toBe(true)
  })

  /**
   * `transitionProperty` is the one that made this worth deriving. It takes
   * `<single-transition-property>`, which is `all | <custom-ident>` — so `'color'` is an ordinary
   * property name, not a near-miss for the `colors` utility value. The type layer rejected it and
   * suggested `'colors'`, which emits seven declarations instead of one.
   */
  test('accepts a property name where the grammar asks for one', () => {
    expect(acceptsAuthorIdent('transitionProperty')).toBe(true)
    expect(acceptsAuthorIdent('willChange')).toBe(true)
  })

  /**
   * A quoted string is not an identifier. `content` and `gridTemplateAreas` take `<string>`, and
   * exempting them would buy nothing — a quoted value is not shaped like a token path, so it
   * never reaches the check this exempts a property from — while giving up `content: 'noen'`.
   */
  test('a string-taking property is not identifier-taking', () => {
    expect(acceptsAuthorIdent('content')).toBe(false)
    expect(acceptsAuthorIdent('gridTemplateAreas')).toBe(false)
  })
})

/**
 * The committed table against the two files it is derived from.
 *
 * `src/index.ts` is generated by `pnpm mdn` and committed, so bumping `csstype` in
 * `@bamboocss/types` or `mdn-data` here leaves it describing the previous version — silently,
 * because a stale keyword list does not fail anything, it just quietly starts rejecting a value
 * CSS added or accepting one it removed.
 *
 * Re-derived here and compared as data rather than as text, so this cannot fail over formatting.
 */
describe('the committed table', () => {
  test('matches csstype and mdn-data as installed', () => {
    const derived = readCssPropertyValues(allCssProperties)

    expect([...cssGlobalKeywords].sort()).toEqual(derived.globals)
    expect([...derived.authorIdent].every(acceptsAuthorIdent)).toBe(true)
    expect(derived.authorIdent.length).toBe(allCssProperties.filter((prop) => acceptsAuthorIdent(prop)).length)

    for (const [property, group] of Object.entries(derived.byProperty)) {
      const expected = new Set([...derived.groups[group]!, ...derived.globals])
      expect([...cssPropertyKeywords(property)].sort(), property).toEqual([...expected].sort())
    }
  })
})
